services:
  app:
    build: . 
    container_name: movie-reservation
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/movie_reservation
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      jwt.secret: GrC65S/xkTiBaYJ9xohSnmFAgZ06O4nZb/M51dl1rCE=
      jwt.expiration: 604800000
      seeders.SeedData: true
      seeders.movies: 1000
      seeders.users: 10
      seeders.reservations: 200
      seeders.showtimes: 100
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: movie_reservation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - "6380:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

